apiVersion: v1
kind: ConfigMap
metadata:
  name: xiaobuadminweb-nginx-config
data:
  default.conf: |
            server {
            charset utf-8;
            server_name localhost;
            listen 80;
            root   /usr/share/nginx/html;
            index   index.php index.html index.htm;
            location / {
               root   /usr/share/nginx/html;
               index index.html index.htm index.php index.jsp;
               client_body_buffer_size 128k;
               client_max_body_size    1000m;
               try_files $uri /index.html;
            }
            # location /admin {
            #     proxy_ignore_client_abort on;
            #     proxy_set_header Host $host;
            #     proxy_set_header X-Real-IP $remote_addr;
            #     proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            #     proxy_pass http://uat-xiaobu-admin:8080/;
            #     client_body_buffer_size 128k;
            #     client_max_body_size    1000m;
            # }
            location ~ \.(js|css|png|jpg|gif|swf|ico|pdf|mov|fla|zip|rar|svg|woff|woff2|eot|ttf|otf)$ {
                expires 6M;
                add_header Last-Modified "";
                log_not_found off;
                try_files $uri =404;
            }
            location ~ /\.(ht|svn|git) {
                deny all;
            }
            }